import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'th' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  th: {
    // Navigation
    'nav.home': 'หน้าหลัก',
    'nav.notifications': 'แจ้งเตือน',
    'nav.add': 'เพิ่ม',
    'nav.summary': 'สรุป',
    'nav.settings': 'ตั้งค่า',
    'nav.store': 'ร้านค้า',
    'nav.transactions': 'รายการ',

    // App Name
    'app.name': 'MoneyMind',
    'app.subtitle': 'ระบบจัดการการเงินส่วนตัวและธุรกิจ',
    'app.tagline': 'จัดการเงินอย่างชาญฉลาด',

    // Auth
    'auth.signin': 'เข้าสู่ระบบ',
    'auth.signup': 'สมัครสมาชิก',
    'auth.email': 'อีเมล',
    'auth.password': 'รหัสผ่าน',
    'auth.fullname': 'ชื่อ-นามสกุล',
    'auth.remember': 'จดจำการล็อกอิน',
    'auth.forgotPassword': 'ลืมรหัสผ่าน?',
    'auth.resetPassword': 'รีเซ็ตรหัสผ่าน',
    'auth.resetPassword.description': 'กรุณากรอกอีเมลของคุณเพื่อรับลิงก์รีเซ็ตรหัสผ่าน',
    'auth.resetPassword.sendEmail': 'ส่งอีเมลรีเซ็ตรหัสผ่าน',
    'auth.resetPassword.newPassword': 'รหัสผ่านใหม่',
    'auth.resetPassword.confirmPassword': 'ยืนยันรหัสผ่านใหม่',
    'auth.resetPassword.newPasswordDescription': 'กรุณากรอกรหัสผ่านใหม่ของคุณ',
    'auth.resetPassword.update': 'เปลี่ยนรหัสผ่าน',
    'auth.resetPassword.passwordMismatch': 'รหัสผ่านไม่ตรงกัน',
    'auth.resetPassword.passwordTooShort': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    'auth.signin.success': 'เข้าสู่ระบบสำเร็จ',
    'auth.signin.welcome': 'ยินดีต้อนรับสู่ MoneyMind',
    'auth.signup.success': 'สมัครสมาชิกสำเร็จ',
    'auth.signup.confirm': 'กรุณาตรวจสอบอีเมลเพื่อยืนยันบัญชี',
    'auth.signout.success': 'ออกจากระบบสำเร็จ',
    'auth.signout.thanks': 'ขอบคุณที่ใช้บริการ MoneyMind',
    'auth.signin.error': 'เข้าสู่ระบบไม่สำเร็จ',
    'auth.signup.error': 'สมัครสมาชิกไม่สำเร็จ',
    'auth.signout.error': 'ออกจากระบบไม่สำเร็จ',
    'auth.signout': 'ออกจากระบบ',
    'auth.or': 'หรือ',
    'auth.guestLogin': 'ทดลองใช้ฟรี (Guest)',
    'auth.guestWarning': 'คุณกำลังใช้งานแบบ Guest - ข้อมูลจะไม่ถูกบันทึกถาวร กรุณาสมัครสมาชิกเพื่อเก็บข้อมูล',
    'category.select': 'เลือกหมวดหมู่',

    // Dashboard
    'dashboard.accounts': 'บัญชี',
    'dashboard.currentBalance': 'ยอดคงเหลือปัจจุบัน',
    'dashboard.income': 'รายรับ',
    'dashboard.expense': 'รายจ่าย',
    'dashboard.recurringIncome': 'รายรับประจำ',
    'dashboard.recurringExpense': 'รายจ่ายประจำ',
    'dashboard.projectedBalance': 'คาดการณ์เงินเหลือ (หลังหักรายจ่ายประจำ)',
    'dashboard.addNew': 'เพิ่มรายการใหม่',
    'dashboard.recurring': 'รายการประจำ',
    'dashboard.recentTransactions': 'รายการล่าสุด',
    'dashboard.noTransactions': 'ยังไม่มีรายการ เริ่มเพิ่มรายการแรกของคุณ',
    'dashboard.viewAll': 'ดูทั้งหมด',

    // Transactions
    'transaction.add': 'เพิ่มรายการ',
    'transaction.income': 'รายรับ',
    'transaction.expense': 'รายจ่าย',
    'transaction.amount': 'จำนวนเงิน (บาท)',
    'transaction.category': 'หมวดหมู่',
    'category.select': 'เลือกหมวดหมู่',
    'transaction.description': 'รายละเอียด (ไม่บังคับ)',
    'transaction.description.placeholder': 'อธิบายรายการ... (ไม่บังคับ)',
    'transaction.priority': 'ระดับความสำคัญ',
    'transaction.recurring': 'รายการประจำ',
    'transaction.save': 'บันทึกรายการ',
    'transaction.validation.amount': 'กรุณากรอกจำนวนเงิน',
    'transaction.validation.category': 'กรุณาเลือกหมวดหมู่',
    'transaction.validation.required': 'กรุณากรอกข้อมูลให้ครบ',
    'transaction.validation.check': 'โปรดตรวจสอบว่าได้กรอกจำนวนเงินและหมวดหมู่',
    'transaction.type': 'ประเภทรายการ',
    'transaction.frequency': 'ความถี่',
    'transaction.startDate': 'วันที่เริ่มต้น',
    'transaction.selectDate': 'เลือกวันที่',
    'transaction.scanSlip': 'ถ่ายสลิป',
    'transaction.attachSlip': 'แนบสลิป',
    'transaction.addRecurringSuccess': 'เพิ่มรายการประจำสำเร็จ',
    'transaction.addSuccess': 'เพิ่มรายการสำเร็จ',
    'transaction.savedSuccessfully': 'ถูกบันทึกแล้ว',
    'transaction.willStart': 'จะเริ่มวันที่',
    'transaction.all': 'รายการทั้งหมด',
    'transaction.search': 'ค้นหารายการ...',
    'transaction.allTypes': 'ทุกประเภท',
    'transaction.allCategories': 'ทุกหมวดหมู่',
    'transaction.noResults': 'ไม่พบรายการที่ตรงกับการค้นหา',
    'transaction.displaySummary': 'สรุปรายการที่แสดง',
    'transaction.balance': 'คงเหลือ',
    'transaction.deleteConfirm': 'ยืนยันการลบรายการ',
    'transaction.deleteWarning': 'คุณแน่ใจหรือไม่ว่าต้องการลบรายการนี้? การดำเนินการนี้ไม่สามารถย้อนกลับได้',
    'transaction.delete': 'ลบรายการ',
    'transaction.deleting': 'กำลังลบ...',
    'transaction.deleteSuccess': 'ลบรายการสำเร็จ',
    'transaction.deleteError': 'ไม่สามารถลบรายการได้',
    'transaction.edit': 'แก้ไขรายการ',
    'transaction.updateSuccess': 'อัพเดทรายการสำเร็จ',
    'transaction.date': 'วันที่',

    // Recurring Transactions
    'recurring.title': 'รายการประจำ',
    'recurring.add': 'เพิ่ม',
    'recurring.summary': 'สรุปรายการประจำที่ใช้งาน',
    'recurring.remaining': 'เงินเหลือ',
    'recurring.allTypes': 'ทุกประเภท',
    'recurring.incomeRecurring': 'รายรับประจำ',
    'recurring.expenseRecurring': 'รายจ่ายประจำ',
    'recurring.noItems': 'ยังไม่มีรายการประจำ',
    'recurring.addFirst': 'เพิ่มรายการประจำแรก',
    'recurring.enabled': 'เปิดใช้งานรายการประจำ',
    'recurring.disabled': 'ปิดใช้งานรายการประจำ',
    'recurring.changesSaved': 'การเปลี่ยนแปลงถูกบันทึกแล้ว',
    'recurring.deleted': 'ลบรายการสำเร็จ',
    'recurring.deletedDesc': 'ถูกลบแล้ว',
    'recurring.confirmDelete': 'คุณต้องการลบรายการนี้หรือไม่?',
    'recurring.active': 'ใช้งาน',
    'recurring.inactive': 'ปิดใช้งาน',
    'recurring.nextPayment': 'ครั้งถัดไป',
    'recurring.history': 'ประวัติการเกิดรายการ',
    'recurring.priorityLegend': 'ระดับความสำคัญ',

    // Priority
    'priority.1': 'จำเป็นมาก (สีแดง)',
    'priority.2': 'จำเป็นสูง (สีส้ม)',
    'priority.3': 'ปานกลาง (สีเหลือง)',
    'priority.4': 'จำเป็นน้อย (สีเขียว)',
    'priority.5': 'ไม่จำเป็น (สีน้ำเงิน)',
    'priority.1.short': 'จำเป็นมาก',
    'priority.2.short': 'จำเป็นสูง',
    'priority.3.short': 'ปานกลาง',
    'priority.4.short': 'จำเป็นน้อย',
    'priority.5.short': 'ไม่จำเป็น',
    'priority.label': 'ความสำคัญ',

    // Frequency
    'frequency.daily': 'รายวัน',
    'frequency.weekly': 'รายสัปดาห์',
    'frequency.monthly': 'รายเดือน',

    // Summary
    'summary.title': 'สรุปรายงาน',
    'summary.filter': 'ตัวกรอง',
    'summary.showFilter': 'แสดงตัวกรอง',
    'summary.hideFilter': 'ซ่อนตัวกรอง',
    'summary.period': 'ช่วงเวลา',
    'summary.today': 'วันนี้',
    'summary.thisMonth': 'เดือนนี้',
    'summary.thisQuarter': 'ไตรมาสนี้',
    'summary.last6Months': '6 เดือนล่าสุด',
    'summary.thisYear': 'ปีนี้',
    'summary.startDate': 'วันที่เริ่มต้น',
    'summary.endDate': 'วันที่สิ้นสุด',
    'summary.category': 'หมวดหมู่',
    'summary.activeFilters': 'ใช้งาน',
    'summary.categories': 'หมวดหมู่',
    'summary.customDateRange': 'ช่วงวันที่กำหนดเอง',
    'summary.clearFilters': 'ล้างตัวกรอง',
    'summary.calendar': 'ปฏิทินรายรับ-รายจ่าย',
    'summary.showCalendar': 'แสดงปฏิทิน',
    'summary.hideCalendar': 'ซ่อนปฏิทิน',
    'summary.selectedDate': 'รายการวันที่เลือก',
    'summary.noTransactions': 'ไม่มีรายการ',
    'summary.chart': 'กราฟรายรับ-รายจ่าย',
    'summary.showChart': 'แสดงกราฟ',
    'summary.hideChart': 'ซ่อนกราฟ',
    'summary.colorScheme': 'สีกราฟ',
    'summary.overviewTitle': 'ภาพรวม',
    'summary.totalIncome': 'รายรับรวม',
    'summary.totalExpense': 'รายจ่ายรวม',
    'summary.netBalance': 'คงเหลือสุทธิ',
    'summary.recurringTitle': 'รายการประจำรายเดือน',
    'summary.topExpenses': 'รายจ่ายสูงสุด',
    'summary.noData': 'ยังไม่มีข้อมูลรายจ่าย',
    'summary.export': 'ส่งออก',
    'summary.pdf': 'รายงาน PDF',
    'summary.excel': 'Excel',

    // Accounts
    'accounts.title': 'บัญชีทั้งหมด',
    'accounts.add': 'เพิ่มบัญชี',
    'accounts.create': 'สร้างบัญชีใหม่',
    'accounts.edit': 'แก้ไขบัญชี',
    'accounts.name': 'ชื่อบัญชี',
    'accounts.namePlaceholder': 'เช่น บัญชีส่วนตัว, บัญชีธุรกิจ',
    'accounts.color': 'สี',
    'accounts.description': 'คำอธิบาย (ไม่บังคับ)',
    'accounts.descriptionPlaceholder': 'อธิบายเกี่ยวกับบัญชีนี้',
    'accounts.budget': 'งบประมาณ (บาท)',
    'accounts.setDefault': 'ตั้งเป็นบัญชีหลัก',
    'accounts.createAccount': 'สร้างบัญชี',
    'accounts.currentAccount': 'บัญชีปัจจุบัน',
    'accounts.noAccounts': 'ยังไม่มีบัญชี',
    'accounts.loading': 'กำลังโหลด...',
    'accounts.default': 'หลัก',
    'accounts.delete': 'ลบบัญชี',
    'accounts.deleteConfirm': 'คุณต้องการลบบัญชีนี้หรือไม่?',
    'accounts.deleteWarning': 'การกระทำนี้จะลบรายการทั้งหมดในบัญชีและไม่สามารถย้อนกลับได้',

    // Settings
    'settings.language': 'ภาษา',
    'settings.thai': 'ภาษาไทย',
    'settings.english': 'ภาษาอังกฤษ',
    'settings.userProfile': 'โปรไฟล์ผู้ใช้',
    'settings.editProfile': 'แก้ไขข้อมูลส่วนตัว',
    'settings.editDisplayName': 'แก้ไขชื่อแสดง',
    'settings.displayName': 'ชื่อแสดง',
    'settings.displayNamePlaceholder': 'กรุณาใส่ชื่อแสดง',
    'settings.changePhone': 'เปลี่ยนเบอร์โทร',
    'settings.phone': 'เบอร์โทร',
    'settings.phonePlaceholder': 'กรุณาใส่เบอร์โทร',
    'settings.changePassword': 'เปลี่ยนรหัสผ่าน',
    'settings.pinSettings': 'ตั้งค่า PIN',
    'settings.notifications': 'การแจ้งเตือน',
    'settings.notificationSettings': 'ตั้งค่าการแจ้งเตือน',
    'settings.budgetAlerts': 'เตือนเมื่อใช้เงินเกินงบ',
    'settings.emailNotifications': 'แจ้งเตือนผ่านอีเมล',
    'settings.smsNotifications': 'แจ้งเตือนผ่าน SMS',
    'settings.accountManagement': 'การจัดการบัญชี',
    'settings.manageAllAccounts': 'จัดการบัญชีทั้งหมด',
    'settings.currencySettings': 'ตั้งค่าสกุลเงิน',
    'settings.primaryCurrency': 'สกุลเงินหลัก',
    'settings.secondaryCurrency': 'สกุลเงินสำรอง',
    'settings.selectPrimaryCurrency': 'เลือกสกุลเงินหลัก',
    'settings.selectSecondaryCurrency': 'เลือกสกุลเงินสำรอง',
    'settings.expenseCategories': 'หมวดหมู่รายจ่าย',
    'settings.manageAllCategories': 'จัดการหมวดหมู่ทั้งหมด',
    'settings.separateByAccount': 'แยกหมวดหมู่ตามบัญชี',
    'settings.keywordManagement': 'จัดการคีย์เวิร์ด',
    'settings.aiExpenseAnalyzer': 'AI วิเคราะห์รายจ่าย',
    'settings.backupRestore': 'สำรองและกู้คืนข้อมูล',
    'settings.autoBackup': 'สำรองข้อมูลอัตโนมัติ',
    'settings.backupNow': 'สำรองข้อมูลตอนนี้',
    'settings.restoreData': 'กู้คืนข้อมูล',
    'settings.exportData': 'ส่งออกข้อมูล',
    'settings.exportPDF': 'ส่งออก PDF',
    'settings.exportExcel': 'ส่งออก Excel',
    'settings.security': 'ความปลอดภัย',
    'settings.twoFactor': 'การยืนยันตัวตน 2 ขั้นตอน',
    'settings.loginHistory': 'ประวัติการเข้าใช้งาน',
    'settings.about': 'เกี่ยวกับแอป',
    'settings.version': 'เวอร์ชัน',
    'settings.terms': 'ข้อตกลงการใช้งาน',
    'settings.privacy': 'นโยบายความเป็นส่วนตัว',
    'settings.help': 'ศูนย์ช่วยเหลือ',
    'settings.liabilities': 'จัดการหนี้สิน',

    // Common
    'common.back': 'กลับ',
    'common.save': 'บันทึก',
    'common.saving': 'กำลังบันทึก...',
    'common.cancel': 'ยกเลิก',
    'common.success': 'สำเร็จ',
    'common.error': 'เกิดข้อผิดพลาด',
    'common.loading': 'กำลังโหลด...',
    'common.confirm': 'ยืนยัน',
    'common.delete': 'ลบ',
    'common.edit': 'แก้ไข',
    'common.close': 'ปิด',
    'common.selectDate': 'เลือกวันที่',
    'common.baht': 'บาท',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.notifications': 'Notifications',
    'nav.add': 'Add',
    'nav.summary': 'Summary',
    'nav.settings': 'Settings',
    'nav.store': 'Store',
    'nav.transactions': 'Transactions',

    // App Name
    'app.name': 'MoneyMind',
    'app.subtitle': 'Personal and Business Financial Management System',
    'app.tagline': 'Smart Money Management',

    // Auth
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullname': 'Full Name',
    'auth.remember': 'Remember Login',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPassword.description': 'Enter your email to receive a password reset link',
    'auth.resetPassword.sendEmail': 'Send Reset Email',
    'auth.resetPassword.newPassword': 'New Password',
    'auth.resetPassword.confirmPassword': 'Confirm New Password',
    'auth.resetPassword.newPasswordDescription': 'Please enter your new password',
    'auth.resetPassword.update': 'Update Password',
    'auth.resetPassword.passwordMismatch': 'Passwords do not match',
    'auth.resetPassword.passwordTooShort': 'Password must be at least 6 characters',
    'auth.signin.success': 'Sign In Successful',
    'auth.signin.welcome': 'Welcome to MoneyMind',
    'auth.signup.success': 'Sign Up Successful',
    'auth.signup.confirm': 'Please check your email to confirm your account',
    'auth.signout.success': 'Sign Out Successful',
    'auth.signout.thanks': 'Thank you for using MoneyMind',
    'auth.signin.error': 'Sign In Failed',
    'auth.signup.error': 'Sign Up Failed',
    'auth.signout.error': 'Sign Out Failed',
    'auth.signout': 'Sign Out',
    'auth.or': 'or',
    'auth.guestLogin': 'Try for Free (Guest)',
    'auth.guestWarning': 'You are using Guest mode - data will not be saved permanently. Please sign up to keep your data.',
    'category.select': 'Select category',

    // Dashboard
    'dashboard.accounts': 'Accounts',
    'dashboard.currentBalance': 'Current Balance',
    'dashboard.income': 'Income',
    'dashboard.expense': 'Expense',
    'dashboard.recurringIncome': 'Recurring Income',
    'dashboard.recurringExpense': 'Recurring Expense',
    'dashboard.projectedBalance': 'Projected Balance (after recurring expenses)',
    'dashboard.addNew': 'Add New',
    'dashboard.recurring': 'Recurring',
    'dashboard.recentTransactions': 'Recent Transactions',
    'dashboard.noTransactions': 'No transactions yet. Start adding your first one.',
    'dashboard.viewAll': 'View All',

    // Transactions
    'transaction.add': 'Add Transaction',
    'transaction.income': 'Income',
    'transaction.expense': 'Expense',
    'transaction.amount': 'Amount (THB)',
    'transaction.category': 'Category',
    'category.select': 'Select category',
    'transaction.description': 'Description (Optional)',
    'transaction.description.placeholder': 'Describe transaction... (Optional)',
    'transaction.priority': 'Priority Level',
    'transaction.recurring': 'Recurring Transaction',
    'transaction.save': 'Save Transaction',
    'transaction.validation.amount': 'Please enter amount',
    'transaction.validation.category': 'Please select category',
    'transaction.validation.required': 'Please fill in all required fields',
    'transaction.validation.check': 'Please check that you have entered amount and category',
    'transaction.type': 'Transaction Type',
    'transaction.frequency': 'Frequency',
    'transaction.startDate': 'Start Date',
    'transaction.selectDate': 'Select Date',
    'transaction.scanSlip': 'Scan Slip',
    'transaction.attachSlip': 'Attach Slip',
    'transaction.addRecurringSuccess': 'Recurring transaction added successfully',
    'transaction.addSuccess': 'Transaction added successfully',
    'transaction.savedSuccessfully': 'has been saved',
    'transaction.willStart': 'will start on',
    'transaction.all': 'All Transactions',
    'transaction.search': 'Search transactions...',
    'transaction.allTypes': 'All Types',
    'transaction.allCategories': 'All Categories',
    'transaction.noResults': 'No transactions match your search',
    'transaction.displaySummary': 'Display Summary',
    'transaction.balance': 'Balance',
    'transaction.deleteConfirm': 'Confirm Delete',
    'transaction.deleteWarning': 'Are you sure you want to delete this transaction? This action cannot be undone.',
    'transaction.delete': 'Delete',
    'transaction.deleting': 'Deleting...',
    'transaction.deleteSuccess': 'Transaction deleted successfully',
    'transaction.deleteError': 'Cannot delete transaction',
    'transaction.edit': 'Edit Transaction',
    'transaction.updateSuccess': 'Transaction updated successfully',
    'transaction.date': 'Date',

    // Recurring Transactions
    'recurring.title': 'Recurring Transactions',
    'recurring.add': 'Add',
    'recurring.summary': 'Active Recurring Summary',
    'recurring.remaining': 'Remaining',
    'recurring.allTypes': 'All Types',
    'recurring.incomeRecurring': 'Recurring Income',
    'recurring.expenseRecurring': 'Recurring Expense',
    'recurring.noItems': 'No recurring transactions yet',
    'recurring.addFirst': 'Add First Recurring',
    'recurring.enabled': 'Recurring transaction enabled',
    'recurring.disabled': 'Recurring transaction disabled',
    'recurring.changesSaved': 'Changes saved',
    'recurring.deleted': 'Deleted successfully',
    'recurring.deletedDesc': 'has been deleted',
    'recurring.confirmDelete': 'Do you want to delete this transaction?',
    'recurring.active': 'Active',
    'recurring.inactive': 'Inactive',
    'recurring.nextPayment': 'Next Payment',
    'recurring.history': 'Execution History',
    'recurring.priorityLegend': 'Priority Legend',

    // Priority
    'priority.1': 'Very Important (Red)',
    'priority.2': 'High Priority (Orange)',
    'priority.3': 'Medium (Yellow)',
    'priority.4': 'Low Priority (Green)',
    'priority.5': 'Not Important (Blue)',
    'priority.1.short': 'Very Important',
    'priority.2.short': 'High Priority',
    'priority.3.short': 'Medium',
    'priority.4.short': 'Low Priority',
    'priority.5.short': 'Not Important',
    'priority.label': 'Priority',

    // Frequency
    'frequency.daily': 'Daily',
    'frequency.weekly': 'Weekly',
    'frequency.monthly': 'Monthly',

    // Summary
    'summary.title': 'Summary Report',
    'summary.filter': 'Filter',
    'summary.showFilter': 'Show Filter',
    'summary.hideFilter': 'Hide Filter',
    'summary.period': 'Period',
    'summary.today': 'Today',
    'summary.thisMonth': 'This Month',
    'summary.thisQuarter': 'This Quarter',
    'summary.last6Months': 'Last 6 Months',
    'summary.thisYear': 'This Year',
    'summary.startDate': 'Start Date',
    'summary.endDate': 'End Date',
    'summary.category': 'Category',
    'summary.activeFilters': 'Active',
    'summary.categories': 'categories',
    'summary.customDateRange': 'custom date range',
    'summary.clearFilters': 'Clear Filters',
    'summary.calendar': 'Income/Expense Calendar',
    'summary.showCalendar': 'Show Calendar',
    'summary.hideCalendar': 'Hide Calendar',
    'summary.selectedDate': 'Selected Date Transactions',
    'summary.noTransactions': 'No transactions',
    'summary.chart': 'Income/Expense Chart',
    'summary.showChart': 'Show Chart',
    'summary.hideChart': 'Hide Chart',
    'summary.colorScheme': 'Chart Color',
    'summary.overviewTitle': 'Overview',
    'summary.totalIncome': 'Total Income',
    'summary.totalExpense': 'Total Expense',
    'summary.netBalance': 'Net Balance',
    'summary.recurringTitle': 'Monthly Recurring',
    'summary.topExpenses': 'Top Expenses',
    'summary.noData': 'No expense data yet',
    'summary.export': 'Export',
    'summary.pdf': 'PDF Report',
    'summary.excel': 'Excel',

    // Accounts
    'accounts.title': 'All Accounts',
    'accounts.add': 'Add Account',
    'accounts.create': 'Create New Account',
    'accounts.edit': 'Edit Account',
    'accounts.name': 'Account Name',
    'accounts.namePlaceholder': 'e.g. Personal, Business',
    'accounts.color': 'Color',
    'accounts.description': 'Description (Optional)',
    'accounts.descriptionPlaceholder': 'Describe this account',
    'accounts.budget': 'Budget (THB)',
    'accounts.setDefault': 'Set as Default Account',
    'accounts.createAccount': 'Create Account',
    'accounts.currentAccount': 'Current Account',
    'accounts.noAccounts': 'No accounts yet',
    'accounts.loading': 'Loading...',
    'accounts.default': 'Default',
    'accounts.delete': 'Delete Account',
    'accounts.deleteConfirm': 'Do you want to delete this account?',
    'accounts.deleteWarning': 'This will delete all transactions in this account and cannot be undone.',

    // Settings
    'settings.language': 'Language',
    'settings.thai': 'Thai',
    'settings.english': 'English',
    'settings.userProfile': 'User Profile',
    'settings.editProfile': 'Edit Profile',
    'settings.editDisplayName': 'Edit Display Name',
    'settings.displayName': 'Display Name',
    'settings.displayNamePlaceholder': 'Enter display name',
    'settings.changePhone': 'Change Phone Number',
    'settings.phone': 'Phone Number',
    'settings.phonePlaceholder': 'Enter phone number',
    'settings.changePassword': 'Change Password',
    'settings.pinSettings': 'PIN Settings',
    'settings.notifications': 'Notifications',
    'settings.notificationSettings': 'Notification Settings',
    'settings.budgetAlerts': 'Budget Alerts',
    'settings.emailNotifications': 'Email Notifications',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.accountManagement': 'Account Management',
    'settings.manageAllAccounts': 'Manage All Accounts',
    'settings.currencySettings': 'Currency Settings',
    'settings.primaryCurrency': 'Primary Currency',
    'settings.secondaryCurrency': 'Secondary Currency',
    'settings.selectPrimaryCurrency': 'Select Primary Currency',
    'settings.selectSecondaryCurrency': 'Select Secondary Currency',
    'settings.expenseCategories': 'Expense Categories',
    'settings.manageAllCategories': 'Manage All Categories',
    'settings.separateByAccount': 'Separate by Account',
    'settings.keywordManagement': 'Keyword Management',
    'settings.aiExpenseAnalyzer': 'AI Expense Analyzer',
    'settings.backupRestore': 'Backup & Restore',
    'settings.autoBackup': 'Auto Backup',
    'settings.backupNow': 'Backup Now',
    'settings.restoreData': 'Restore Data',
    'settings.exportData': 'Export Data',
    'settings.exportPDF': 'Export PDF',
    'settings.exportExcel': 'Export Excel',
    'settings.security': 'Security',
    'settings.twoFactor': 'Two-Factor Authentication',
    'settings.loginHistory': 'Login History',
    'settings.about': 'About App',
    'settings.version': 'Version',
    'settings.terms': 'Terms of Service',
    'settings.privacy': 'Privacy Policy',
    'settings.help': 'Help Center',
    'settings.liabilities': 'Manage Liabilities',

    // Common
    'common.back': 'Back',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.loading': 'Loading...',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.selectDate': 'Select Date',
    'common.baht': 'THB',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'th';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['th']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}